name = "sysadm"
license = "MIT"
licenselink = "https://"
description = "A simple blog"
homepage = "https://sysadm.life"
tags = ["blog"]
features = ["mobile","elegant"]
min_version = "0.59.0"

#relativeURLs = true
#uglyURLs = true

baseURL = "https://sysadm.life"
languageCode = "en-us"
title = "sysadm.life"
copyright = ""
theme = "diary"


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "The escapades of a cloud infrastructure consultant"
enableGitalk = true
# enableAutoDarkMode = true
enableReadingTime = true

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

#[[menu.main]]
#url = "/categories"
#name = "Categories"
#weight = 2

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1
